### ISSUE TITLE
How can I detect the item selected ?

### ISSUE THREAD

**Issue by MrRochito** [michaelbabiy/RMParallax#10]
Hi!, first for your controller.

I need to detect when the user touch in a item, thank you.

greetings

**Comment by michaelbabiy** [comment]
You should be able to add an instance of UITapGestureRecognizer with custom selector to the image view when you are setting up RMParallax (fun setupRMParallax()) in RMParallax.swift class.

This would be my first suggestion. I haven't tried it myself, but I see no reason for this NOT to work.

**Comment by MrRochito** [comment]
Perfect!, you are right! ;) thanks
