### ISSUE TITLE
Redraw on rotation

### ISSUE THREAD

**Issue by lpaniccia** [michaelbabiy/RMParallax#18]
hey there! 
I love the parallax effect, but I noticed when using it on an iPad it doesn't redraw when the device is rotated. [Video example of the bug.](http://recordit.co/rxpTgaAow0)

**Comment by michaelbabiy** [comment]
Thank you for bringing this up... When I get some time this / next week, I will try adding support for rotation. Feel free to submit a pull request if you implement it before me...
