### ISSUE TITLE
Xcode Warning: Use of string literal for Objective-C selectors is deprecated

### ISSUE THREAD

**Issue by lpaniccia** [michaelbabiy/RMParallax#19]
Xcode is giving a warning:

> /RMParallax-master/RMParallax/RMParallax/RMParallax.swift:85:52: Use of string literal for Objective-C selectors is deprecated; use '#selector' instead

Xcode's suggestion seems to fix it, so it should be easy to resolve.

![rmparallaxwarning](https://cloud.githubusercontent.com/assets/1945204/14131119/35e9f5f2-f606-11e5-8615-9a2e55b8c166.png)

**Comment by michaelbabiy** [comment]
Thanks for mentioning it. I've updated the project to support Swift 2.2.
