### ISSUE TITLE
Scrolling error

### ISSUE THREAD

**Issue by stsmkrv** [michaelbabiy/RMParallax#2]
"fatal error: unexpectedly found nil while unwrapping an Optional value" in RMParallax
![2015-02-02 10 31 21](https://cloud.githubusercontent.com/assets/6969912/6001138/53b97ffe-aaf7-11e4-8baf-c57dac28ca19.png)

**Comment by michaelbabiy** [comment]
Thank you. I'll look into it when I get free time today / tomorrow.

**Comment by michaelbabiy** [comment]
By the way, how can I reproduce this crash? Do you remember what you did? Thank you.

**Comment by michaelbabiy** [comment]
Fixed in a latest commit.
