### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by stsmkrv** [michaelbabiy/RMParallax#3]
Sometimes I notice strange behavior - for a moment main screen with "Hello" text appears.
This is mainly happens when I scroll to the next page not until the end. But sometimes i saw same behavior during normal pages scrolling.

**Comment by ghost** [comment]
Same here. Issue could be restricted only to 8.2 though.

—
Solomon, Sam

**Comment by stsmkrv** [comment]
For better understanding http://youtu.be/K37loQRQoCw

**Comment by michaelbabiy** [comment]
I'll look into it sometime this week (a bit busy at work). If you guys have a moment, and would like to contribute, feel free to submit a merge request. Thank you.
