### ISSUE TITLE
problem with gesture

### ISSUE THREAD

**Issue by lostpupil** [michaelbabiy/RMParallax#7]
Here is the problem, I would like to add swipe to trigger completionHandler on last child of those items.
So, I can swipe to main view which I want?
but I notice that collection view will ignore the swipe gesture if I have more than 1 picture.
Is there anyway to add a swipe and navigate to main view?

**Comment by michaelbabiy** [comment]
You are more then welcome to fork the project and implementing it yourself. It is possible.
