### ISSUE TITLE
Strange behevior when used with UITabBarController as main view controller

### ISSUE THREAD

**Issue by ghost** [michaelbabiy/RMParallax#8]
I use RMParallax exactly the way you suggested in README.md. I put the code into viewDidLoad() of the main view controller, which inherits UITabBarController. But here is the issue:

The bottom of my main view should look like
![img_0094](https://cloud.githubusercontent.com/assets/5637174/7553667/5c552cb6-f738-11e4-8306-ba2897bc3ca9.jpg)

But after the RMParallax view faded out at first launch, it looks like
![img_0092](https://cloud.githubusercontent.com/assets/5637174/7553669/646cc9c2-f738-11e4-81f3-d71970106823.jpg)

And when I click on the rightmost tab, the page turns black.
![img_0093](https://cloud.githubusercontent.com/assets/5637174/7553672/6af62202-f738-11e4-8cd4-100a5aa90bc6.jpg)

At second launch (where I read NSUserDefaults entry and bypass RMParallax), everything works well. I know this issue may related to my way of use of UITabBarController, but do you have any idea why this occurs? Thank you.

**Comment by michaelbabiy** [comment]
I don't believe RMParallax is the problem here... If you want, I can take a look at your code and see if I can identify the issue. Please email me.

Thanks.

**Comment by ghost** [comment]
Michael,

Thanks for your help.  I’ve temporarily set my repository on Bitbucket public:

Git:
    https://fengzee@bitbucket.org/fengzee-zzh/cocktail.git

or source code:
    https://bitbucket.org/fengzee-zzh/cocktail/src/ https://bitbucket.org/fengzee-zzh/cocktail/src/
if you don’t need to build it. To save your time.

The project is under the /PeaksApp folder.

The code I use RMParallax is in ViewController.swift:
    https://bitbucket.org/fengzee-zzh/cocktail/src/750b4ac70c538586907bf3e1feb8bbf89728ea83/PeaksApp/Peaks/ViewController.swift?at=master https://bitbucket.org/fengzee-zzh/cocktail/src/750b4ac70c538586907bf3e1feb8bbf89728ea83/PeaksApp/Peaks/ViewController.swift?at=master

This is my first Swift toy project so please expect to see very messy code and a lot of comments that is not English. I hope that’s not a problem for identifying the issue. :D

Thank you for your time again!

Fengzee
